/*
Modelagem Básica 
- Entidade = Tabela
- Campos = Atributos 
*/

Cliente

Nome - Caracter(30)
CPF - Numerico(11)
email - Caracter(30)
telefone - Caracter(30)
endereco - Caracter(100)
sexo - Caracter(1)

/* Processos de Modelagem */

/* Fase 01 e Fase 02 - AD ADM de dados */

Modelagem Conceitual - Rascunho
Modelagem Lógica - Qualquer programa de modelagem

/* Fase 3 - DBA / AD */
Modelagem Física - Scripts de banco

/* Iniciando a modelagem Física */

/* Criando o Banco de Dados */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE (
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES; 
/* show tables e um ponteiramento 
para o comando select no dicionario de dados*/

STATUS - PARA VERIFICAR A BASE CORRENTE  

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* SINTAXE BASICA DE INSERÇÃO - INSERT INTO TABELA... */

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES('REYDNER', 'M', 'REYDNERJORGE@GOO.COM', 
00000000000, '22393110', 'RUA ESTACIO DE LIMA - UDIA - MG');

INSERT INTO CLIENTE VALUES('REYD', 'M', 'REYDJORGE@GOO.COM', 
00000000000, '223393110', 'RUA ESTACIO DE LIMA - UDIA - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('NATHALIA', 'F',
'RUA SERRA NEGRA - SJ - UDIA - MG', '3499999999', 887774856);


/* O COMANDO SELECT
SELECAO -
PROJECAO - E OQUE SE PROJETA NA TELA
JUNCAO - 
*/

SELECT NOW() as DATA_HORA, 'FELIPE MAFRA' as PROFESSOR;

SELECT 'REYD';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

/* USAR ESSE COMANDO APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE

/* FILTRANDO DADO COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO COM WHERE */

SELECT NOME, SEXO  FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'F';

/* UTILIZANDO O LIKE */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%MG';


